"""
AudioEngine Public Command API

This module defines the complete set of commands that the GUI may send to the audio engine.
Commands are immutable and are designed to be sent via multiprocessing queues to the AudioService.

Version: 1.0 (FROZEN)
Stability: Stable - breaking changes require major version bump

Design Principles:
- All commands are frozen dataclasses (immutable)
- No Qt imports or GUI dependencies
- No side effects or logic in command classes
- Commands are routed via AudioService to the AudioEngine
- Order of delivery is not guaranteed for most commands

Architecture:
- GUI sends commands to AudioService via _audio_cmd_q (multiprocessing.Queue)
- AudioService routes PlayCueCommand directly to engine.play_cue()
- AudioService routes other commands to engine.handle_command()
- Engine processes commands asynchronously
- Engine emits events back via _audio_evt_q for GUI consumption
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional

API_VERSION = "1.0"

# ==============================================================================
# TRANSPORT COMMANDS
# ==============================================================================

@dataclass(frozen=True, slots=True)
class TransportPlay:
    """Request playback to resume (if paused) or start from first cue.
    
    Invariant: Only meaningful if transport is in "paused" or "stopped" state.
    Status: Unimplemented (reserved for future use).
    """
    pass


@dataclass(frozen=True, slots=True)
class TransportStop:
    """Request complete playback stop and engine shutdown.
    
    Invariant: After this command, the AudioService process should terminate gracefully.
    Invariant: All active cues will be stopped.
    Invariant: This is the ONLY command that triggers engine shutdown.
    Invariant: No further commands will be processed after this command is sent.
    """
    pass


@dataclass(frozen=True, slots=True)
class TransportPause:
    """Request playback to pause (all cues fade out, but remain in memory).
    
    Invariant: Cues can be resumed without restarting decode.
    Status: Unimplemented (reserved for future use).
    """
    pass


@dataclass(frozen=True, slots=True)
class TransportNext:
    """Request skip to next cue (future use - currently unimplemented)."""
    pass


@dataclass(frozen=True, slots=True)
class TransportPrev:
    """Request skip to previous cue (future use - currently unimplemented)."""
    pass


# ==============================================================================
# CUE PLAYBACK COMMANDS
# ==============================================================================

@dataclass(frozen=True, slots=True)
class PlayCueCommand:
    """Request playback of a single audio file (cue).
    
    The GUI generates a unique cue_id that identifies this playback session.
    The engine treats cue_id as opaque and includes it in all related events.
    Multiple cues can play simultaneously (layered).
    
    Invariants:
    - cue_id is generated by the GUI and uniquely identifies one playback instance.
    - file_path must exist and be a valid, readable audio file.
    - The engine will probe the file for metadata in the audio service process.
    - If auto_fade_on_new is enabled, previously active cues will fade out.
    - Each PlayCueCommand will emit CueStartedEvent and eventually CueFinishedEvent.
    - The same cue_id from the command will appear in CueStartedEvent and CueFinishedEvent.
    
    Fields:
        cue_id (str): Unique identifier generated by the GUI (required, opaque to engine).
        file_path (str): Absolute path to audio file (required, must exist).
        track_id (str or None): App-specific track ID for logging (optional).
        gain_db (float): Initial gain in dB (default 0.0 = unity, -120 = silence).
        in_frame (int): Start at this frame (default 0 = beginning).
        out_frame (int or None): Stop at this frame (None = end of file).
        fade_in_ms (int): Fade-in duration in ms (default 0 = no fade).
        fade_out_ms (int): Fade-out duration in ms (default 0 = no fade).
        fade_curve (str): Fade shape: "equal_power" or "linear" (default "equal_power").
        loop_enabled (bool): Loop from out_frame to in_frame if True.
        layered (bool): If True, don't auto-fade existing cues.
        total_seconds (float or None): Pre-computed duration in seconds (optional).
    """
    cue_id: str
    file_path: str
    track_id: Optional[str] = None
    gain_db: float = 0.0
    in_frame: int = 0
    out_frame: Optional[int] = None
    fade_in_ms: int = 0
    fade_out_ms: int = 0
    fade_curve: str = "equal_power"
    loop_enabled: bool = False
    layered: bool = False
    total_seconds: Optional[float] = None


@dataclass(frozen=True, slots=True)
class StopCueCommand:
    """Request immediate stop of a playing cue.
    
    Invariants:
    - cue_id must have been created by a prior PlayCueCommand.
    - Stopping a non-existent cue is silently ignored (no error).
    - If fade_out_ms > 0, the cue will fade to silence before stopping.
    
    Fields:
        cue_id (str): Unique identifier of the cue to stop (required).
        fade_out_ms (int): Fade-out duration in ms (default 0 = immediate stop).
        fade_curve (str): Fade shape: "linear" or "equal_power" (default "linear").
    """
    cue_id: str
    fade_out_ms: int = 0
    fade_curve: str = "linear"


@dataclass(frozen=True, slots=True)
class FadeCueCommand:
    """Request a dynamic gain fade on a specific cue.
    
    Allows smooth transitions between gain levels without stopping playback.
    
    Invariants:
    - cue_id must refer to an active, playing cue.
    - Fading a non-existent cue is silently ignored (no error).
    - If target_db <= -120, the cue will be silenced and may be stopped.
    - Multiple FadeCueCommand calls cancel prior fades and start a new one.
    
    Fields:
        cue_id (str): Unique identifier of the cue to fade (required).
        target_db (float): Target gain in dB (required). E.g., 0.0 = unity, -6.0 = half.
        duration_ms (int): Fade duration in ms (required). Must be > 0.
        curve (str): Curve shape: "equal_power" or "linear" (required).
    """
    cue_id: str
    target_db: float
    duration_ms: int
    curve: str


# ==============================================================================
# GAIN & FADE COMMANDS
# ==============================================================================

@dataclass(frozen=True, slots=True)
class SetMasterGainCommand:
    """Request change to the master output gain.
    
    Status: Reserved for future implementation. Currently ignored.
    
    Fields:
        gain_db (float): Master gain in dB (0.0 = unity, no scaling).
    """
    gain_db: float


@dataclass(frozen=True, slots=True)
class UpdateCueCommand:
    """Request update to properties of a specific cue while playing.
    
    Only provided fields will be updated; others remain unchanged.
    All fields are optional to allow selective updates of cue properties.
    
    Invariants:
    - cue_id must refer to an active cue (or is silently ignored).
    - Changes are applied immediately in the decoder and output processes.
    - Loop boundary changes (in_frame, out_frame) take effect on next loop iteration.
    
    Fields:
        cue_id (str): Unique identifier of the cue to update (required).
        in_frame (Optional[int]): Start frame (0-based), or None to not update.
        out_frame (Optional[int]): End frame (exclusive), or None to not update.
        gain_db (Optional[float]): Gain in dB (0.0 = unity), or None to not update.
        loop_enabled (Optional[bool]): Enable/disable looping, or None to not update.
    """
    cue_id: str
    in_frame: Optional[int] = None
    out_frame: Optional[int] = None
    gain_db: Optional[float] = None
    loop_enabled: Optional[bool] = None


@dataclass(frozen=True, slots=True)
class SetAutoFadeCommand:
    """Request enable/disable of auto-fade-on-new behavior.
    
    When enabled, starting a new cue will automatically fade out all previous cues
    (unless layered=True in PlayCueCommand). This is a persistent setting.
    
    Invariants:
    - Setting persists across multiple PlayCueCommand calls.
    - Can be toggled at any time (takes effect on next PlayCueCommand).
    - Does not affect currently playing cues.
    
    Fields:
        enabled (bool): If True, enable auto-fade. If False, allow layered playback.
    """
    enabled: bool


@dataclass(frozen=True, slots=True)
class OutputFadeTo:
    """Request a fade of a cue's output gain to a target level.
    
    Used internally by output_process to smoothly transition gain levels.
    
    Fields:
        cue_id (str): Unique identifier of the cue to fade.
        target_db (float): Target gain in dB.
        duration_ms (int): Fade duration in milliseconds.
        curve (str): Fade curve shape: "linear" or "equal_power".
    """
    cue_id: str
    target_db: float
    duration_ms: int
    curve: str = "equal_power"


# ==============================================================================
# CONFIGURATION COMMANDS
# ==============================================================================

@dataclass(frozen=True, slots=True)
class OutputSetDevice:
    """Request switch to a different audio output device.
    
    Status: Partially implemented (command recognized, may have limitations).
    
    Invariants:
    - device can be a device index (int) or name (str).
    - Invalid device IDs will be rejected and logged (no exception).
    
    Fields:
        device (int or str): Audio device index or friendly name.
    """
    device: object  # int or str


@dataclass(frozen=True, slots=True)
class OutputSetConfig:
    """Request change to audio output configuration (sample rate, channels, block size).
    
    Status: Partially implemented (may trigger stream restart).
    
    Changes require re-opening the audio stream. All active cues will be
    re-rendered with the new sample rate.
    
    Invariants:
    - sample_rate must be a valid hardware rate (e.g., 44100, 48000, 96000).
    - channels must be 1 (mono) or 2 (stereo).
    - block_frames must be power of 2 (e.g., 256, 512, 1024, 2048).
    
    Fields:
        sample_rate (int): Output sample rate in Hz.
        channels (int): Number of output channels (1 or 2).
        block_frames (int): Audio block size in frames.
    """
    sample_rate: int
    channels: int
    block_frames: int


@dataclass(frozen=True, slots=True)
class OutputListDevices:
    """Request list of available audio output devices.
    
    Status: Implemented.
    
    Triggers an internal ("devices", [...]) event with available audio devices.
    
    Invariant: Does not change any audio settings, purely informational.
    """
    pass

