"""
This type stub file was generated by cyright.
"""

from typing import Type
from numpy import ndarray

class plot:
    def __init__(self, audio: Type[ndarray]) -> None:
        ...
    
    @property
    def audio(self): # -> NDArray:
        ...
    
    def plot_waveform(self, painter=..., pen=..., scroll_pos: int = ..., height: int = ..., width: int = ..., position: int = ..., thickness: float = ..., duration: int = ..., scale: float = ..., in_point: int = ..., out_point: int = ...): # -> None:
        ...
    


