"""
This type stub file was generated by cyright.
"""

from array import array

def plot_waveform(painter=..., audio_level_array: array[float] = ..., left_pos: int = ..., waveform_height: int = ..., scale: int = ..., pad: int = ..., height: int = ...): # -> None:
    ...

